finished the testsjob

diff --git a/.github/workflows/assignment3.yml b/.github/workflows/assignment3.yml
--- a/.github/workflows/assignment3.yml
+++ b/.github/workflows/assignment3.yml
@@ -5,6 +5,8 @@ jobs:
   build:
     runs-on: ubuntu-latest
     steps:
+      - name: log of start workflow time
+        run: echo -e "$(date -Iminutes)\nOmri Weinstein, Gal Trodel\n" > log.txt
       - name: Checkout
         uses: actions/checkout@v4
       - name: Set up Docker Buildx
@@ -15,6 +17,18 @@ jobs:
           context: ./booksServer
           tags: books:latest, ${{ secrets.USERNAME }}/books:latest
           outputs: type=docker,dest=/tmp/image.tar
+      - name: Check build status and log result
+        run: |
+          if [ -f /tmp/image.tar ]; then
+            echo -e "image successfully built\n" >> log.txt
+          else
+            echo -e "image not able to be built\n" >> log.txt
+          fi
+      - name: Upload log file
+        uses: actions/upload-artifact@v3
+        with:
+          name: log
+          path: log.txt
       - name: Upload artifact
         uses: actions/upload-artifact@v3
         with:
@@ -39,7 +53,12 @@ jobs:
       - name: run image in container
         run: docker run -e MONGO_URL="mongodb://mongodb:27017/BooksDB" --network books-net -p5001:8000 books &
       - name: Check container is running
-        run: docker ps
+        run: |
+          if docker ps --filter "name=books-container" --filter "status=running" | grep books-container; then
+            echo -e "Container up and running\n" >> log.txt
+          else
+            echo -e "Container failed to run\n" >> log.txt
+          fi
       #     2. set up python and pytest environment
       - name: Checkout
         uses: actions/checkout@v4
@@ -56,24 +75,21 @@ jobs:
         run: |
           cd tests
           pytest -v assn3_tests.py > assn3_test_results.txt
+        continue-on-error: true
+      - name: Check test results and log
+        run: |
+          if [ $? -eq 0 ]; then
+            echo -e "tests succeeded\n" >> log.txt
+          else
+            echo -e "tests failed\n" >> log.txt
+          fi
       - name: upload test results
-        if: always() # always perform this step even if tests fail, to see results
         uses: actions/upload-artifact@v3
         with:
-          name: GH_test_results
+          name: assn3_test_results
           path: tests/assn3_test_results.txt
-      #     The following steps will only execute if tests succeeded
-      - name: Set DATE
-        run: echo "DATE=$(date -I)" >> $GITHUB_ENV
-      - name: Log in to Docker Hub
-        uses: docker/login-action@v2
+      - name: Upload log file
+        uses: actions/upload-artifact@v3
         with:
-          username: ${{ secrets.DOCKER_COURSE_USERNAME }}
-          password: ${{ secrets.DOCKER_COURSE_PASSWORD }}
-      - name: push image with "latest" and date tags to DH
-        run: |
-          docker push ${{ secrets.DOCKER_COURSE_USERNAME }}/wordsvr-v2
-          docker tag ${{ secrets.DOCKER_COURSE_USERNAME }}/wordsvr-v2 \
-          ${{ secrets.DOCKER_COURSE_USERNAME }}/wordsvr-v2:${{ env.DATE }}
-          docker push \
-          ${{ secrets.DOCKER_COURSE_USERNAME }}/wordsvr-v2:${{ env.DATE }}
+          name: log
+          path: log.txt
